englisher/dashbord/pricing/urls.py
from django.urls import path
from .views import (PricingListView,
                    PricingCreateView,
                    PricingUpdateView,
                    PricingDeleteView)


urlpatterns = [
     path("pricing/list/", PricingListView.as_view(), name="pricing-list"),
     path("pricing/create/",
          PricingCreateView.as_view(),
          name="pricing-create"),
     path("pricing/edit/<pk>/",
          PricingUpdateView.as_view(),
          name="pricing-edit"),
     path("pricing/delete/<pk>/",
          PricingDeleteView.as_view(),
          name="pricing-delete"),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',
        auth_views.LoginView.as_view(redirect_authenticated_user=True),
        name='login'),
    path('logout/', auth_views.LogoutView.as_view(),
        name='logout'),
    path('password/change/',
        auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('dashboard')),
        name='change-password'),
        # success_url=reverse_lazy('category-list')
    path('', include("englisher.urls")),
    path('dashboard/', include("englisher.dashbord.pricing.urls")),
    path('dashboard/', include("englisher.dashbord.freevideo.urls")),
    path('dashboard/', include("englisher.dashbord.testimonials.urls")),
    path('dashboard/', include("englisher.dashbord.sponsor.urls")),
    path('dashboard/', include("englisher.dashbord.foundrfeature.urls")),
    path('dashboard/', include("englisher.dashbord.englisherfeature.urls")),
    path('dashboard/', include("englisher.dashbord.team.urls")),
    path('dashboard/', include("englisher.dashbord.solo.urls")),
    path('dashboard/', include("englisher.dashbord.email.urls")),
    path('dashboard/', include("englisher.dashbord.mailbox.urls")),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

englisher/models.py
from django.db import models
from solo.models import SingletonModel


COLOR_CHOICES = (
    ("success", "Green"),
    ("danger", "Red"),
    ("warning", "Yellow"),
)

class SiteConfiguration(SingletonModel):
    # header_logo = models.ImageField(upload_to="images/logos/")
    # footer_logo = models.ImageField(upload_to="images/logos/")
    # footer_about = models.CharField(max_length=1000)
    # address = models.CharField(max_length=1000, blank=True, null=True)
    # phone = models.CharField(max_length=12, blank=True, null=True)
    # email = models.CharField(max_length=250, blank=True, null=True)
    # facebook_page = models.URLField(blank=True, null=True)
    # youtube_channel = models.URLField(blank=True, null=True)
    # Slider Configuration
    slider_image = models.ImageField(upload_to="images/slider/")
    slider_title = models.CharField(max_length=250, blank=True, null=True)
    slider_body = models.CharField(max_length=1000, blank=True, null=True)
    #  Numers Configuration
    student_number = models.IntegerField(default=500)
    free_video_number = models.IntegerField(default=100)
    courses_number = models.IntegerField(default=20)
    hours_number = models.IntegerField(default=500)

    def __str__(self):
        return "Site Configuration"

    class Meta:
        verbose_name = "Site Configuration"


class Pricing(models.Model):
    title = models.CharField(max_length=250)
    # price = models.FloatField()
    plan_included = models.TextField()
    payment_url = models.URLField()
    box_color = models.CharField(max_length=10,choices=COLOR_CHOICES)
    active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class FreeVideo(models.Model):
    title = models.CharField(max_length=250)
    image = models.ImageField(upload_to="images/freevideo/")
    iframe = models.TextField()
    video_link = models.URLField()
    active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Testimonials(models.Model):
    author = models.CharField(max_length=250)
    author_image = models.ImageField(upload_to="images/testimonials/")
    what_he_say = models.TextField()
    active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.author

class Sponsor(models.Model):
    sponsor_name = models.CharField(max_length=250)
    sponsor_image = models.ImageField(upload_to="images/sponsors/")
    active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.sponsor_name


class AboutFounder(SingletonModel):
    founder_name = models.CharField(max_length=250)
    founder_image = models.ImageField(upload_to="images/founder/")
    body = models.TextField()

    def __str__(self):
        return "About Founder"

    class Meta:
        verbose_name = "About Founder"


class FoundrFeature(models.Model):
    icon = models.CharField(max_length=100)
    value = models.CharField(max_length=250)
    body = models.TextField()
    active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.value


class AboutEnglisher(SingletonModel):
    englisher_name = models.CharField(max_length=250)
    englisher_image = models.ImageField(upload_to="images/englisher/")
    body = models.TextField()

    def __str__(self):
        return "About Englisher"

    class Meta:
        verbose_name = "About Englisher"


class EnglisherFeature(models.Model):
    icon = models.CharField(max_length=100)
    value = models.CharField(max_length=250)
    body = models.TextField()
    active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.value


class Team(models.Model):
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to="images/team/")
    jop = models.CharField(max_length=250, blank=True, null=True)
    about = models.TextField()
    # facebook_link = models.URLField(blank=True, null=True)
    # twitter_link = models.URLField(blank=True, null=True)
    # linkedin_link = models.URLField(blank=True, null=True)
    active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Email(models.Model):
    email = models.EmailField(max_length=250, unique=True)
    active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.email


class Mail(models.Model):
    subject = models.CharField(max_length=250)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-id",)

    def __str__(self):
        return self.name

englisher/dashbord/pricing/views.py
from englisher.models import Pricing


from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from django.urls import reverse_lazy


class PricingMixin(LoginRequiredMixin,
                    PermissionRequiredMixin):
    model = Pricing
    fields = "__all__"


class GetSuccessUrlOverridePricingMixin:
    def get_success_url(self):
        return reverse_lazy("pricing-list")


class PricingListView(PricingMixin, ListView):
    template_name = "dashboard/dash_template/pricing/list.html"
    permission_required = "englisher.view_pricing"


class PricingCreateView(PricingMixin,
                         GetSuccessUrlOverridePricingMixin,
                         CreateView):
    template_name = "dashboard/dash_template/pricing/form.html"
    permission_required = "englisher.add_pricing"


class PricingUpdateView(PricingMixin,
                         GetSuccessUrlOverridePricingMixin,
                         UpdateView):
    template_name = "dashboard/dash_template/pricing/form.html"
    permission_required = "englisher.change_pricing"


class PricingDeleteView(PricingMixin,
                         GetSuccessUrlOverridePricingMixin,
                         DeleteView):
    permission_required = "englisher.delete_pricing"

templates/dashboard/dash_template/pricing/form.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block title %}{% if object %}Edit {{object}}{% else %}Create New Pricing{% endif %}
{% endblock title %}
{% block pagelevelcss %}
<link href="{% static 'dashboard/assets/css/apps/invoice-add.css' %}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/plugins/dropify/dropify.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/assets/css/forms/theme-checkbox-radio.cs' %}s">
<link href="{% static 'dashboard/plugins/flatpickr/flatpickr.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'dashboard/plugins/flatpickr/custom-flatpickr.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'dashboard/assets/css/scrollspyNav.css' %}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="{% static 'dashboard/plugins/editors/markdown/simplemde.min.css' %}">
<link href="{% static 'dashboard/plugins/file-upload/file-upload-with-preview.min.css' %}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/assets/css/forms/switches.css' %}">
{% endblock pagelevelcss %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'pricing-list' %}">Pricings</a></li>
<li class="breadcrumb-item active" aria-current="page"><span>{% if object %}Edit {{object}}{% else %}Create New Pricing{% endif %}</span></li>
{% endblock breadcrumb %}

{% block content %}
<div class="row invoice layout-top-spacing layout-spacing">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        
        <div class="doc-container">
            <div class="row">
                <div class="col-xl-9">
                    <div class="invoice-content">
                        <div class="invoice-detail-body"> 
                            <div class="invoice-detail-header">

                                <div class="row justify-content-around">
                                    <div class="col-xl-12 invoice-address-company">

                                        <h4>{% if object %}Update {{edit}}:-{% else %}Create New Pricing:-{% endif %}</h4>
                                        
                                        <div class="invoice-address-company-fields">
                                            <form id="supmit-form" method="post" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div class="form-group row pt-3">
                                                    <label for="{{ form.title.id_for_label }}" class="col-sm-3 col-form-label col-form-label-sm">{{ form.title.label }}</label>
                                                    <div class="col-sm-9">
                                                        {{ form.title|add_class:'form-control form-control-sm' }}
                                                    </div>
                                                    {% for error in form.title.errors %}
                                                        <span class="text-danger">{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                                {% comment %} <div class="form-group row pt-3">
                                                    <label for="{{ form.price.id_for_label }}" class="col-sm-3 col-form-label col-form-label-sm">{{ form.price.label }}</label>
                                                    <div class="col-sm-9">
                                                        {{ form.price|add_class:'form-control form-control-sm' }}
                                                    </div>
                                                    {% for error in form.price.errors %}
                                                        <span class="text-danger">{{ error }}</span>
                                                    {% endfor %}
                                                </div> {% endcomment %}
                                                <div class="form-group row pt-3">
                                                    <label for="{{ form.active.id_for_label }}" class="col-sm-3 col-form-label col-form-label-sm">{{ form.active.label }}</label>
                                                    <div class="col-sm-9">
                                                        <label class="switch s-icons s-outline s-outline-success mr-2">
                                                            {{ form.active }}
                                                            <span class="slider round"></span>
                                                        </label>
                                                        {% for error in form.active.errors %}
                                                        <span class="text-danger">{{ error }}</span>
                                                        {% endfor %}
                                                    </div>
                                                </div>
                                                <div class="form-group row pt-3">
                                                    <label for="{{ form.plan_included.id_for_label }}" class="col-sm-3 col-form-label col-form-label-sm">{{ form.plan_included.label }}</label>
                                                    <div class="col-sm-9">
                                                        {{ form.plan_included|add_class:"demo1"|append_attr:"id:test" }}
                                                    </div>
                                                    {% for error in form.plan_included.errors %}
                                                        <span class="text-danger">{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                                <div class="form-group row pt-3">
                                                    <label for="{{ form.payment_url.id_for_label }}" class="col-sm-3 col-form-label col-form-label-sm">{{ form.payment_url.label }}</label>
                                                    <div class="col-sm-9">
                                                        {{ form.payment_url|add_class:'form-control form-control-sm' }}
                                                    </div>
                                                    {% for error in form.payment_url.errors %}
                                                        <span class="text-danger">{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                                <div class="form-group row pt-3">
                                                    <label for="{{ form.box_color.id_for_label }}" class="col-sm-3 col-form-label col-form-label-sm">{{ form.box_color.label }}</label>
                                                    <div class="col-sm-9">
                                                        {{ form.box_color|add_class:'form-control form-control-sm' }}
                                                    </div>
                                                    {% for error in form.box_color.errors %}
                                                        <span class="text-danger">{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                            </form>    
                                        </div>
                                        
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3">
                    <div class="invoice-actions-btn">
                        <div class="invoice-action-btn">
                            <div class="row">
                                <div class="col-xl-12 col-md-4">
                                    <button class="btn btn-success btn-download w-100" form="supmit-form" type="submit">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock content %}

{% block pageleveljs %}
<script src="{% static 'dashboard/plugins/dropify/dropify.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/flatpickr/flatpickr.js' %}"></script>
<script src="{% static 'dashboard/assets/js/apps/invoice-add.js' %}"></script>
<script src="{% static 'dashboard/assets/js/scrollspyNav.js' %}"></script>
<script src="{% static 'dashboard/plugins/editors/markdown/simplemde.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/editors/markdown/custom-markdown.js' %}"></script>
<script src="{% static 'dashboard/plugins/file-upload/file-upload-with-preview.min.js' %}"></script>
    <script>
        var firstUpload = new FileUploadWithPreview('myFirstImage',{
            images: {
                baseImage: '{% if object.main_photo.url is not None %}{{object.main_photo.url}}{% else %}{% static 'assets/img/plaseholder.png' %}{% endif %}',
            }
        });
        
        {% for f in photo_form %}
        $('#{{f.value.id_for_label}}').dropify({
            defaultFile: "{% if f.instance.value.url is not None %}{{f.instance}}{% endif %}",
            messages: { 'default': 'Click to Upload Image', 'replace': 'Upload or Drag n Drop' },
        });
        {% endfor %}
    </script>
<script>
    new SimpleMDE({
    element: document.getElementById('test'),
    spellChecker: false,
    forceSync: true,
    });
</script>
{% endblock pageleveljs %}

templates/dashboard/dash_template/pricing/list.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block title %}Pricing{% endblock title %}
{% block pagelevelcss %}
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/plugins/table/datatable/datatables.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/plugins/table/datatable/dt-global_style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'dashboard/assets/css/forms/theme-checkbox-radio.css' %}">
<link href="{% static 'dashboard/assets/css/apps/invoice-list.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'dashboard/assets/css/tables/table-basic.css' %}" rel="stylesheet" type="text/css" />
{% endblock pagelevelcss %}

{% block breadcrumb %}
<li class="breadcrumb-item active" aria-current="page"><span>Pricing</span></li>
{% endblock breadcrumb %}

{% block content %}
<div class="row layout-top-spacing">
    <div class="col-xl-12 col-lg-12 col-sm-12 layout-spacing">
        <div class="widget-content widget-content-area br-6">
            <table id="invoice-list" class="table table-hover" style="width:100%">
                <thead>
                    <tr>
                        <th class="checkbox-column" style="width: 10px;"> # </th>
                        <th>Title</th>
                        {% comment %} <th>Price</th> {% endcomment %}
                        <th>Box Color</th> 
                        <th>Active</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pricing in object_list %}
                    <tr>
                        <td class="checkbox-column"> 1 </td>
                        <td>
                            <div class="d-flex">
                                <p class="align-self-center mb-0 user-name">{{pricing}}</p>
                            </div>
                        </td>
                        {% comment %} <td>{{pricing.price}}</td> {% endcomment %}
                        <td>{{pricing.get_box_color_display}}</td>
                        <td>{{pricing.active}}</td>
                        <td class="text-center">
                            <ul class="table-controls">
                                <li><a href="{% url 'pricing-edit' pricing.id %}" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2 text-success"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></a></li>
                                <li>
                                    <form action="{% url 'pricing-delete' pricing.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn p-0" style="background-color:transparent" >
                                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2 text-danger">
                                                <polyline points="3 6 5 6 21 6"></polyline>
                                                <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2">
                                                </path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line>
                                            </svg>
                                        </button>
                                    </form>
                                </li>
                            </ul>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}
    

{% block pageleveljs %}
<script src="{% static 'dashboard/plugins/table/datatable/datatables.js' %}"></script>
<script src="{% static 'dashboard/plugins/table/datatable/button-ext/dataTables.buttons.min.js' %}"></script>
<script>
var invoiceList = $('#invoice-list').DataTable({
    "dom": "<'inv-list-top-section'"+ 
    "<'row'" +
    "<'col-12 d-flex justify-content-between'l" +
    "<'dt-action-buttons float-right'B>>>>",
    buttons: [
        {
            text: 'Add New',
            className: 'btn btn-primary btn-sm',
            action: function(e, dt, node, config ) {
                window.location.href = "{% url 'pricing-create' %}";
            }
        }
    ],
    searching: false,
    "order": [[ 1, "asc" ]],
    "stripeClasses": [],
    "lengthMenu": [10, 20, 50, 100],
    "pageLength": 10
});
</script>
{% endblock pageleveljs %}